travis:
  secure:
    BINSTAR_TOKEN: ecCpV8F82iyXSyM48bP8RoeVQdaJxV/hrcrw81UpglHRl3oMkiPP/iSKRJ0Q/9IKtTmsKC/YunHuyZyzoVPqiPH9raJY03/IBNBGAVIaPw9PYN2mz+iOC4WZXTqUfPcmfc9VEDZhA1bTciVNnEMX6MeVfRJA/T14dvkrtFAutvC1mMUFwM9QLPyz1JQaHrFJFNNX9f0o7FhwMEMNF94ScUjoKn6OI6aSW/U2expY8nrD8St7j/rZd8xpcYdYj/yamlZsIOH55daEg/RiCsEUabAbCRUqYJLPSaIpJxL9jYCPnPbeB+bsDqKwpSRnDkbDjV1TgKDA+gdFozPxL0n/+mvJgxhlIc2DWSrg7xjriXhlDAdjaeyjkmIjr8k5SaImn+9bGFY1FaC86/F8HT7HanDMxirTN24k86INQx9zL/t6VCuOspSDIMSZkJgGOiPVI1iZ/dfnnRWziZRbEtY3NVARM/ZcCm6CT1q1QTe0ju1Q/CBHLKGkizDJcOjF2DhfbYpbX7ecoocoAFU44dG1WUhv72q9zhkRU4v/aCnTlppUdZnjpF5vQk0QBcDElu7eBWmLxS5lrRlz2cy2Ti7GYv18qrUnm0l95P4BWR4ctSo/s110IlKCYX17b5+Js+hlXCqkH8+t7C0YDIgEqShOeImoRqfn+pvET8tCPHpxuzk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
